apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: bluehub.azurecr.io/meateam/migration:1.0
      restartPolicy: Never
  backoffLimit: 4
